### PR TITLE
Add progress bar for download status and fixed state update issue

### PR DESCRIPTION
**Pull request by The-Robin-Hood**
@tuhinpal  - Made Changes regarding Issue #2

### CODE REVIEW

**Comment by tuhinpal** [comment]
Hey! Can you please give me a working example? I mean can you deploy that to your account and send me a link?

**Comment by The-Robin-Hood** [comment]
You can check the demo here 
https://hls-downloader-wheat.vercel.app/


https://github.com/tuhinpal/hls-downloader/assets/32297581/d14ca9a6-1c0c-4ac0-8960-cd3fc4903e6b

**Comment by tuhinpal** [comment]
Every time after video is created, it shows a spinner and the screen is freezing there.

**Comment by tuhinpal** [comment]
- Please remove `await sleep (.*) //wait for state to update`. 
- Please remove the SVG of segment stitching

**Comment by The-Robin-Hood** [comment]
Will remove the svg but it doesnt freezes and that sleep is to wait for the state to update. If the sleep is remove then the state is not getting update.

**Comment by tuhinpal** [comment]
Sounds good

**Comment by tuhinpal** [comment]
Gave you collaborator access! Please merge it after done..

Thank you so much for contributing!

**Comment by The-Robin-Hood** [comment]
Do you want to remove the loader svg ? or let it be there ? @tuhinpal

**Comment by tuhinpal** [comment]
I think remove it!

**Pull request merged**
